default: &default
  adapter: mysql2
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hearthstone_API_development

test:
  <<: *default
  database: hearthstone_API_test

production:
  <<: *default
  database: hearthstone_API_production
  username: <%= ENV['HEARTHSTONE_API_DATABASE_USERNAME'] %>
  password: <%= ENV['HEARTHSTONE_API_DATABASE_PASSWORD'] %>
